### ISSUE TITLE
window above the leaderboard does not align for me in full-screen mode (playing stretched 1920x1440 on a 2540x1440 monitor)

### ISSUE THREAD

**Issue by NotEnoughSpeed** [sylae/tm-map-info#3]

**Comment by sylae** [comment]
Thanks for the report! If possible, could you attach a screenshot of this in action so we know what to look for?

**Comment by NotEnoughSpeed** [comment]
![image](https://user-images.githubusercontent.com/50259775/218267644-31ef4efc-74ac-438a-9acb-ba7fcf3ee7a2.png)

**Comment by XertroV** [comment]
Should be fixed in the next patch for ~all configurations. (e.g., a scaled down records table on a stretched resolution)
![image](https://user-images.githubusercontent.com/1046448/218388714-161d5f6e-67f6-4f9c-b888-7cf2b520ff5d.png)
